### PR TITLE
Add tiddlywiki ind readme-md and bug-fixed in readme-md too

### PR DESCRIPTION
**Pull request by ghost**
Hi, 

This pull request serves to help and resolve this open issue: [awesome-local-first/issues/1](https://github.com/schickling/awesome-local-first/issues/1). I've added tiddlywiki here to this repository. I hope to help and I hope you enjoy this pr

### CODE REVIEW

**Comment by linonetwo** [comment]
Thanks, please add `[TidGi](https://github.com/tiddly-gittly/TidGi-Desktop) - Customizable personal knowledge-base with git as backup manager.` too! This is a new-user-friendly desktop version, and is popular in China.

**Comment by ghost** [comment]
> Thanks, please add [TidGi](https://github.com/tiddly-gittly/TidGi-Desktop) - Customizable personal knowledge-base with git as backup manager. too! This is a new-user-friendly desktop version, and is popular in China.

thank you for feedback, so I've done it on this pull-request, now.

**Comment by linonetwo** [comment]
LGTM  @schickling

**Comment by ghost** [comment]
thanks @linonetwo, @schickling

**Pull request merged**
